# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

source =  ~/.config/hypr/conf/autostart.conf
source =  ~/.config/hypr/conf/environment_variables.conf
source =  ~/.config/hypr/conf/input.conf
source =  ~/.config/hypr/conf/keybindings.conf
source =  ~/.config/hypr/conf/look_and_feel.conf
source =  ~/.config/hypr/conf/plugins.conf
source =  ~/.config/hypr/conf/windows_and_workspaces.conf
source =  ~/.config/hypr/monitors.conf
source =  ~/.config/hypr/private.conf
