#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,BreezeX-Dark
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_PASSWORD_RECALL,1

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_DRM_DEVICES,/dev/dri/by-path/pci-0000:10:00.0-card:/dev/dri/by-path/pci-0000:30:00.0-card

env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = ELECTRON_OZONE_PLATFORM_HINT,auto
