##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

#===Bug fix=============================================
windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
#================================================

workspace = special:special, gapsin:5, gapsout:30
windowrule = match:fullscreen yes, immediate yes
windowrule = match:class fcitx5, no_focus yes, float yes

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
  name = move-YTMusic-scratchpad
  match:initial_title = YouTube Music
  workspace = special
}

windowrule {
    name = float-btop
    match:class = btop
    float = yes
}

windowrule {
    name = Virtual-Box
    match:class = VirtualBox Machine
    fullscreen = yes
}

windowrule {
    name = GPU Screen Recorder
    match:class = gsr-ui
    fullscreen = yes
}

windowrule {
    name = Vesktop
    match:class = vesktop
    opacity = 0.9
}

windowrule {
    name = Thunar
    match:class = thunar
    opacity = 0.9
}

windowrule {
    name = yad
    match:class = yad
    float = yes
    stay_focused = yes
    no_blur = yes
    border_size = 0
    rounding = 0
}